name: tabata_timer
description: 타바타 & 인터벌 타이머 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  audioplayers: ^6.0.0
  vibration: ^2.0.0
  wakelock_plus: ^1.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
